# Generated by Django 4.2.16 on 2024-11-10 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POI",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("isPublic", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("reactions", models.IntegerField(default=0)),
                ("content", models.JSONField(blank=True, null=True)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
