# Generated by Django 4.2.16 on 2024-12-07 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pois", "0002_alter_poi_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="poi",
            name="createdAt",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="poi",
            name="updatedAt",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
