# Generated by Django 4.2.16 on 2024-12-08 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pois", "0003_poi_createdat_poi_updatedat"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoiInteractions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[("reaction", "Reaction"), ("comment", "Comment")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="pois.poi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poi_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
