# Generated by Django 4.2.16 on 2024-12-08 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pois", "0005_rename_created_at_poiinteractions_createdat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poiinteractions",
            old_name="poi",
            new_name="poiId",
        ),
        migrations.RenameField(
            model_name="poiinteractions",
            old_name="user",
            new_name="userId",
        ),
    ]
