name: CI

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mapquester_frontend/package-lock.json

    - name: Install Frontend Dependencies
      working-directory: mapquester_frontend
      run: npm ci

    - name: Run Frontend Linting
      working-directory: mapquester_frontend
      run: npm run lint

    - name: Run Frontend Tests
      working-directory: mapquester_frontend
      run: npm test

  # backend:
  #   name: Backend Checks
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.11'
  #       cache: 'pip'
  #       cache-dependency-path: mapquester_backend/requirements-dev.txt

  #   - name: Install Backend Dependencies
  #     working-directory: mapquester_backend
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install -r requirements-dev.txt

  #   - name: Run Backend Linting
  #     working-directory: mapquester_backend
  #     run: pylint mapquester_backend

  #   - name: Run Backend Tests
  #     working-directory: mapquester_backend
  #     run: |
  #       python -m pytest tests/ --cov=mapquester_backend --cov-report=term-missing