name: Deploy MapQuester Backend to AWS Elastic Beanstalk

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  deploy:
    name: Deploy MapQuester Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Adjust to your project's Python version
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Replace with your AWS region
    
    - name: Install EB CLI
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Prepare Backend Deployment Package
      run: |
        # Change to the backend directory
        cd mapquester_backend
        
        # Create a deployment package (ZIP)
        zip -r ../deploy.zip . -x '.git*' -x '.github*'
        
        # Return to root directory
        cd ..
    
    - name: Deploy to Elastic Beanstalk
      env:
        EB_APPLICATION: mapquester-backend  # Replace with your EB application name
        EB_ENVIRONMENT: mapquester-backend-prod  # Replace with your EB environment name
        DEPLOY_VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        # Ensure we're in the correct context
        cd mapquester_backend
        
        # Initialize EB if not already done
        eb init -r us-west-2 -p python-3.12 $EB_APPLICATION
        
        # Use and deploy to specific environment
        eb use $EB_ENVIRONMENT
        eb deploy $EB_ENVIRONMENT --label $DEPLOY_VERSION
    
    - name: Deployment Notification
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment of MapQuester Backend to Elastic Beanstalk successful! 🚀
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}